### ISSUE TITLE
A question and a suggestion

### ISSUE THREAD

**Issue by lostsoul6** [NockyCZ/CS2-ReservedSlots#1]
Hello @NockyCZ ,

In reserve slot method 3 , does it mean that if we have 10 slots for players and max players is set to 10 and an admin joins , then the server can have 11 players while we set max players as 10 ?

Also a kick type where the last player to have joined the server is kicked would be a good idea . If we kick by highest ping or random , we might kick the first fragger of the server and unbalance the game .

**Comment by NockyCZ** [comment]
```In reserve slot method 3 , does it mean that if we have 10 slots for players and max players is set to 10 and an admin joins , then the server can have 11 players while we set max players as 10 ?```
Yes

```Also a kick type where the last player to have joined the server is kicked would be a good idea . If we kick by highest ping or random , we might kick the first fragger of the server and unbalance the game .```
Good idea, i will add it

**Comment by NockyCZ** [comment]
Added in v1.0.1

**Comment by crashzk** [comment]
@NockyCZ 

**Kick type** - Works only if Reserved slots method is set to 0, 1 or 2.
- 0 - Players will be kicked randomly
- 1 - Players will be kicked by highest ping
- 2 - Players will be kicked by highest score

Wouldn't option 2 be better due to the lower score? Or did I misunderstand?

Kicking the best scoring player can create an imbalance as mentioned.

And why not the option to kick the last player who connected?

**Comment by lostsoul6** [comment]
@NockyCZ  @crashzk I agree , the lowest scorer of the server must be kicked . it usually is the last player who joined as well .

**Comment by NockyCZ** [comment]
Oh my bad :D I read it wrong

**Comment by lostsoul6** [comment]
@NockyCZ , will it be fixed ?

**Comment by NockyCZ** [comment]
Yeah

**Comment by NockyCZ** [comment]
Added :)
